### ISSUE TITLE
Flask not running? Help?

### ISSUE THREAD

**Issue by joelpeckham** [SAU-Senior-Project-2022/train_backend#1]
Howdy backend folks. The flask server seems to not be working in the latest branch. [Here's a video showing my issue.](https://www.youtube.com/watch?v=sw6RiisY9PU)

**Comment by AlexOConnorHub** [comment]
TL;DR: It's working right, just wait about 15 seconds, then check again.

As you might have noticed, it's running two docker containers as part of the one system. The mariadb container takes about ten seconds to start up, and is required to be up before flask will run right. The solution we employed was to simply have a restart policy of `restart on failure`. The flask container will crash about 6-7 times based on our observations, but after about 15 seconds (once the mariadb container is up), it works fine.

**Comment by joelpeckham** [comment]
## Still not working.
Still no joy. :( I'm assuming there's something in my environment that's causing the issue, but I thought docker was supposed to fix that! Whatever.
## What I've tried
- At first, I wasn't seeing any restart behavior. Flask just reported 'exited' and never attempted a restart.
- But after changing  `restart: on-failure` to `restart: always`, I began to see the 6-7 restarts you described.
- However, after those 7 restart attempts, flask seems to get stuck in a 'restarting' state, and never actually starts.
## What I need
- I need some way to get debug output and figure out what's going on here. 
- I tried adding the `--debug` flag in `src/Dockerfile` -- Edit: this flag seems to have been removed from main.py?
- Currently working on modifying main.py. Will report back if I get this fixed.

**Comment by joelpeckham** [comment]
#Ok it's working??
##Whwat I did:
- I screwed around adding a bunch of debug print statements and try/except blocks to main.py and server.py.
- After several rounds of compose ups, downs, rebuilds, etc, it just started working out of the blue.
- I have no idea what changed. 
- I'm gonna go cry.
- Issue closed, but I'm mad about it.
